"""animal dwh_time

Revision ID: 05f6cfa0a762
Revises: cbd1504b5579
Create Date: 2023-05-10 20:45:16.395760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f6cfa0a762'
down_revision = 'cbd1504b5579'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_settings', sa.Column('dwh_time', sa.DateTime(), nullable=True))
    op.add_column('animals', sa.Column('dwh_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'dwh_time')
    op.drop_column('animal_settings', 'dwh_time')
    # ### end Alembic commands ###
