"""tags

Revision ID: 1507d157e00b
Revises: 9943ce093527
Create Date: 2025-01-27 15:57:01.314837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1507d157e00b'
down_revision = '9943ce093527'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('strikes', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('trials', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trials', 'tags')
    op.drop_column('strikes', 'tags')
    op.drop_column('blocks', 'tags')
    # ### end Alembic commands ###
