"""pose add prob and bodypart

Revision ID: 1bdde0835580
Revises: 25453a165ecb
Create Date: 2023-08-13 11:19:27.621675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bdde0835580'
down_revision = '25453a165ecb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pose_estimations', sa.Column('prob', sa.Float(), nullable=True))
    op.add_column('pose_estimations', sa.Column('bodypart', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pose_estimations', 'bodypart')
    op.drop_column('pose_estimations', 'prob')
    # ### end Alembic commands ###
