"""is_manual reward

Revision ID: 25453a165ecb
Revises: e7d4db7c6ed2
Create Date: 2023-07-11 15:36:56.514598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25453a165ecb'
down_revision = 'e7d4db7c6ed2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('is_manual', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rewards', 'is_manual')
    # ### end Alembic commands ###
