"""new trial settings

Revision ID: 2b284814f887
Revises: 49e07b3e3725
Create Date: 2024-12-16 12:45:11.585643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b284814f887'
down_revision = '49e07b3e3725'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trials', sa.Column('bug_speed', sa.Float(), nullable=True))
    op.add_column('trials', sa.Column('trial_bugs', sa.String(), nullable=True))
    op.add_column('trials', sa.Column('bug_sizes', sa.String(), nullable=True))
    op.add_column('trials', sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('trials', 'bug_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trials', sa.Column('bug_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('trials', 'extra')
    op.drop_column('trials', 'bug_sizes')
    op.drop_column('trials', 'trial_bugs')
    op.drop_column('trials', 'bug_speed')
    # ### end Alembic commands ###
