"""migration name

Revision ID: 2c7e4c5eb745
Revises: 633f4d8a3f07
Create Date: 2026-02-15 12:31:32.380005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7e4c5eb745'
down_revision = '633f4d8a3f07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
