"""reward skipped

Revision ID: 2f050449dcd3
Revises: e2aea892d59b
Create Date: 2025-02-14 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f050449dcd3'
down_revision = 'e2aea892d59b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strikes', sa.Column('reward_skipped', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strikes', 'reward_skipped')
    # ### end Alembic commands ###
