"""animal dwh_key

Revision ID: 36f30073f8cb
Revises: 05f6cfa0a762
Create Date: 2023-05-10 21:26:23.009851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36f30073f8cb'
down_revision = '05f6cfa0a762'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_settings', sa.Column('dwh_key', sa.Integer(), nullable=True))
    op.drop_column('animal_settings', 'dwh_time')
    op.add_column('animals', sa.Column('dwh_key', sa.Integer(), nullable=True))
    op.drop_column('animals', 'dwh_time')
    op.add_column('blocks', sa.Column('dwh_key', sa.Integer(), nullable=True))
    op.add_column('experiments', sa.Column('dwh_key', sa.Integer(), nullable=True))
    op.add_column('strikes', sa.Column('dwh_key', sa.Integer(), nullable=True))
    op.add_column('trials', sa.Column('dwh_key', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trials', 'dwh_key')
    op.drop_column('strikes', 'dwh_key')
    op.drop_column('experiments', 'dwh_key')
    op.drop_column('blocks', 'dwh_key')
    op.add_column('animals', sa.Column('dwh_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('animals', 'dwh_key')
    op.add_column('animal_settings', sa.Column('dwh_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('animal_settings', 'dwh_key')
    # ### end Alembic commands ###
