"""agent_label

Revision ID: 3b1921f54db3
Revises: 1507d157e00b
Create Date: 2025-01-29 09:27:40.202007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1921f54db3'
down_revision = '1507d157e00b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('agent_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'agent_label')
    # ### end Alembic commands ###
