"""exit_hole in trials

Revision ID: 49e07b3e3725
Revises: 5212e29d3497
Create Date: 2024-04-14 13:09:08.324498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e07b3e3725'
down_revision = '5212e29d3497'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.add_column('trials', sa.Column('exit_hole', sa.String(), nullable=True))
    op.add_column('trials', sa.Column('bug_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trials', 'bug_type')
    op.drop_column('trials', 'exit_hole')
    op.drop_table('users')
    # ### end Alembic commands ###
