"""analysis error

Revision ID: 55d78234dc71
Revises: bf1876bf6497
Create Date: 2023-05-17 09:43:58.405757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d78234dc71'
down_revision = 'bf1876bf6497'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
