"""video dwh_key

Revision ID: 686530bb491d
Revises: db2ab487a71f
Create Date: 2023-08-16 16:57:49.653446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686530bb491d'
down_revision = 'db2ab487a71f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('dwh_key', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'dwh_key')
    # ### end Alembic commands ###
