"""remove old fields in Block

Revision ID: 9943ce093527
Revises: 2b284814f887
Create Date: 2024-12-24 15:12:27.290048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9943ce093527'
down_revision = '2b284814f887'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('holes_height_scale', sa.Float(), nullable=True))
    op.drop_column('blocks', 'is_anticlockwise')
    op.drop_column('blocks', 'reward_type')
    op.drop_column('blocks', 'target_drift')
    op.drop_column('blocks', 'time_between_bugs')
    op.drop_column('blocks', 'bug_height')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('bug_height', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('blocks', sa.Column('time_between_bugs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('blocks', sa.Column('target_drift', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blocks', sa.Column('reward_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blocks', sa.Column('is_anticlockwise', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('blocks', 'holes_height_scale')
    # ### end Alembic commands ###
