"""migration name

Revision ID: bed84ac01e0c
Revises: 2f050449dcd3
Create Date: 2026-02-10 16:53:12.868226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bed84ac01e0c'
down_revision = '2f050449dcd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('bug_mapped_background', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'bug_mapped_background')
    # ### end Alembic commands ###
