"""strike_error

Revision ID: bf1876bf6497
Revises: 36f30073f8cb
Create Date: 2023-05-16 10:07:23.372297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1876bf6497'
down_revision = '36f30073f8cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strikes', sa.Column('analysis_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strikes', 'analysis_error')
    # ### end Alembic commands ###
