"""first migration

Revision ID: cbd1504b5579
Revises: fdef62f70679
Create Date: 2023-05-01 14:49:18.208073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbd1504b5579'
down_revision = 'fdef62f70679'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('arena', sa.String(), nullable=True),
    sa.Column('bug_types', sa.String(), nullable=True),
    sa.Column('reward_bugs', sa.String(), nullable=True),
    sa.Column('background_color', sa.String(), nullable=True),
    sa.Column('reward_any_touch_prob', sa.Float(), nullable=True),
    sa.Column('exit_hole', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('animal_id', sa.String(), nullable=True),
    sa.Column('cameras', sa.String(), nullable=True),
    sa.Column('num_blocks', sa.Integer(), nullable=True),
    sa.Column('extra_time_recording', sa.Integer(), nullable=True),
    sa.Column('time_between_blocks', sa.Integer(), nullable=True),
    sa.Column('experiment_path', sa.String(), nullable=True),
    sa.Column('arena', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('animal_id', sa.String(), nullable=True),
    sa.Column('arena', sa.String(), nullable=True),
    sa.Column('experiment_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('animal_id', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('arena', sa.String(), nullable=True),
    sa.Column('bug_types', sa.String(), nullable=True),
    sa.Column('reward_bugs', sa.String(), nullable=True),
    sa.Column('background_color', sa.String(), nullable=True),
    sa.Column('reward_any_touch_prob', sa.Float(), nullable=True),
    sa.Column('exit_hole', sa.String(), nullable=True),
    sa.Column('animal_id_key', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id_key'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('num_trials', sa.Integer(), nullable=True),
    sa.Column('trial_duration', sa.Integer(), nullable=True),
    sa.Column('iti', sa.Integer(), nullable=True),
    sa.Column('block_type', sa.String(), nullable=True),
    sa.Column('bug_types', sa.String(), nullable=True),
    sa.Column('bug_speed', sa.Integer(), nullable=True),
    sa.Column('bug_size', sa.Integer(), nullable=True),
    sa.Column('is_default_bug_size', sa.Boolean(), nullable=True),
    sa.Column('exit_hole', sa.String(), nullable=True),
    sa.Column('reward_type', sa.String(), nullable=True),
    sa.Column('reward_bugs', sa.String(), nullable=True),
    sa.Column('reward_any_touch_prob', sa.Float(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('movement_type', sa.String(), nullable=True),
    sa.Column('is_anticlockwise', sa.Boolean(), nullable=True),
    sa.Column('target_drift', sa.String(), nullable=True),
    sa.Column('bug_height', sa.Integer(), nullable=True),
    sa.Column('time_between_bugs', sa.Integer(), nullable=True),
    sa.Column('background_color', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('folder', sa.String(), nullable=True),
    sa.Column('model_group_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['model_group_id'], ['model_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('animal_id', sa.String(), nullable=True),
    sa.Column('arena', sa.String(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temperatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('arena', sa.String(), nullable=True),
    sa.Column('sensor', sa.String(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('in_block_trial_id', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('bug_trajectory', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cam_name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('calc_fps', sa.Float(), nullable=True),
    sa.Column('num_frames', sa.Integer(), nullable=True),
    sa.Column('animal_id', sa.String(), nullable=True),
    sa.Column('frames', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('compression_status', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pose_estimations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cam_name', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('animal_id', sa.String(), nullable=True),
    sa.Column('angle', sa.Float(), nullable=True),
    sa.Column('engagement', sa.Float(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('is_hit', sa.Boolean(), nullable=True),
    sa.Column('is_reward_bug', sa.Boolean(), nullable=True),
    sa.Column('is_climbing', sa.Boolean(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('bug_x', sa.Float(), nullable=True),
    sa.Column('bug_y', sa.Float(), nullable=True),
    sa.Column('bug_type', sa.String(), nullable=True),
    sa.Column('bug_size', sa.Integer(), nullable=True),
    sa.Column('in_block_trial_id', sa.Integer(), nullable=True),
    sa.Column('prediction_distance', sa.Float(), nullable=True),
    sa.Column('calc_speed', sa.Float(), nullable=True),
    sa.Column('projected_strike_coords', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('projected_leap_coords', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('max_acceleration', sa.Float(), nullable=True),
    sa.Column('strike_frame', sa.Integer(), nullable=True),
    sa.Column('leap_frame', sa.Integer(), nullable=True),
    sa.Column('arena', sa.String(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('trial_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predictor_name', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_predictions')
    op.drop_table('strikes')
    op.drop_table('pose_estimations')
    op.drop_table('videos')
    op.drop_table('trials')
    op.drop_table('temperatures')
    op.drop_table('rewards')
    op.drop_table('model_versions')
    op.drop_table('blocks')
    op.drop_table('animal_settings')
    op.drop_table('schedules')
    op.drop_table('model_groups')
    op.drop_table('experiments')
    op.drop_table('animals')
    # ### end Alembic commands ###
