"""pose add frame_id

Revision ID: db2ab487a71f
Revises: 1bdde0835580
Create Date: 2023-08-15 04:39:52.232019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2ab487a71f'
down_revision = '1bdde0835580'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pose_estimations', sa.Column('frame_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pose_estimations', 'frame_id')
    # ### end Alembic commands ###
