"""remove animal settings

Revision ID: e2aea892d59b
Revises: 3b1921f54db3
Create Date: 2025-02-10 11:13:31.948997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2aea892d59b'
down_revision = '3b1921f54db3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal_settings')
    op.drop_column('animals', 'bug_types')
    op.drop_column('animals', 'reward_any_touch_prob')
    op.drop_column('animals', 'exit_hole')
    op.drop_column('animals', 'reward_bugs')
    op.drop_column('animals', 'background_color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('background_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('animals', sa.Column('reward_bugs', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('animals', sa.Column('exit_hole', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('animals', sa.Column('reward_any_touch_prob', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('animals', sa.Column('bug_types', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('animal_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('animal_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arena', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bug_types', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reward_bugs', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('background_color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reward_any_touch_prob', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('exit_hole', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('animal_id_key', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dwh_key', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['animal_id_key'], ['animals.id'], name='animal_settings_animal_id_key_fkey'),
    sa.PrimaryKeyConstraint('id', name='animal_settings_pkey')
    )
    # ### end Alembic commands ###
