"""dwh pose estimation

Revision ID: e7d4db7c6ed2
Revises: 55d78234dc71
Create Date: 2023-07-05 18:58:23.348194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d4db7c6ed2'
down_revision = '55d78234dc71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pose_estimations', sa.Column('dwh_key', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pose_estimations', 'dwh_key')
    # ### end Alembic commands ###
