version: '3'

services:
  arena:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-arena
    container_name: arena
    privileged: true
    volumes:
    - ../Arena:/arena
    restart: always
    command: "flask run --host=0.0.0.0"
    ports:
      - 3350:8888
      - 3351:5000
    environment:
      - FLASK_APP=api.py
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8

  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-app
    container_name: pogona_hunter
    restart: always
    ports:
     - 8080:8080

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 27017:27017
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example