version: '3'

services:
  arena:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-arena
    container_name: arena
    privileged: true
    restart: always
    ports:
      - 3350:8888
      - 3351:5000

  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-app
    container_name: pogona_hunter
    restart: always
    ports:
     - 8080:8080

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672